language: node_js
node_js:
  - "stable"
before_script:
  - npm prune
jobs:
  include:
    - stage: test
      script: echo "Testing Started ..."
      script: echo "Linting ..."
      script: npm run lint
      script: echo "Test ..."
      script: npm run test
      script: echo "Create Documentation ..."
      script: npm run doc
after-success:
  - echo "Semantic Release Deployment .."
  - npm run semantic-release
branches:
  only:
  - master
